language: node_js

node_js:
  - 12.16.2

jobs:
  include:
    - name: "Jest + Enzyme Tests"
      script:
        - update yarn
        - npm install
        - npm run test
    - name: "Linter"
      script:
        - update yarn
        - npm install
        - npm run eslint